#!/usr/bin/env bash

iDIR="$HOME/.config/hypr/mako/icons"
backlight=$(brightnessctl -m | awk -F, '{print substr($4, 0, length($4)-1)}')

# Get brightness
get_backlight() {
	echo "$backlight%"
}

# Get icons
get_icon() {
        current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "20") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "20") && ("$current" -le "40") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "40") && ("$current" -le "60") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "60") && ("$current" -le "80") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "80") && ("$current" -le "100") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $backlight %"
}

# Increase brightness
inc_backlight() {
	brightnessctl set 10%+ && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl set 10%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
