#!/bin/bash

DIR=$HOME/Pictures/wallpapers/
# Use find command to search for image files in DIR and its subdirectories
PICS=($(find ${DIR} -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.gif" \)))

RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

if [[ $(pidof swww-daemon) ]]; then
  swww kill
fi


swaybg -m fill -i ${DIR}/${RANDOMPICS}
## notify-send "${RANDOMPICS}"
